New logo
Gold-Squadron/XY-Fleet pull request #81
Opened 2024-02-05 12:57 UTC by any1-source

added all designed logos for our website.
Didnt adjust the colorset for the website. still needs fixing.

2024-02-09 14:47 UTC, N0ah-S requested changes
Please rename the files to something usable

2024-02-10 13:13 UTC, Lucaauem approved these changes
Looking good (but please rename the files)

2024-02-13 15:21 UTC, any1-source commented
es gib

2024-02-13 15:26 UTC, merged

2024-02-14 10:50 UTC, N0ah-S commented
Apply changes and re-open